version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=quitzone.local
      - VIRTUAL_PORT=8080
    links:
      - client
      - server
    networks:
      - proxynet
      - default
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    networks:
      - default
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_DATABASE=quitzone
      - DB_USERNAME=quitzone
      - DB_PASSWORD=HLdW3KbaWvRCEq8PUz3xku8iraYEVIq6w3wDPJe/ggI=
    volumes:
      - ./server:/var/www
    links:
      - db:db
    networks:
      - default
      - proxynet
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "quitzone", "-pHLdW3KbaWvRCEq8PUz3xku8iraYEVIq6w3wDPJe/ggI="]
      timeout: 20s
      retries: 10
    ports:
      - 7003:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=quitzone
      - MYSQL_USER=quitzone
      - MYSQL_PASSWORD=HLdW3KbaWvRCEq8PUz3xku8iraYEVIq6w3wDPJe/ggI=
    networks:
      - default
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: db
      PMA_USER: quitzone
      PMA_PASSWORD: HLdW3KbaWvRCEq8PUz3xku8iraYEVIq6w3wDPJe/ggI=

volumes:
  database:
    driver: local

networks:
  proxynet:
    external:
      name: proxy_network
  default:
